# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen
  commands:
    # Generate Doxygen XML for Breathe
    - cd docs && doxygen Doxyfile
    # Build Sphinx documentation
    - python -m sphinx -b html docs/source $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: docs/requirements.txt
